import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Home/Navbar";
import Footer from "@/components/Home/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Your Booking | Qrent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //   <body className={inter.className}>
    <div>
      <Navbar />
      {children}
    </div>
    //     </body>
    // </html>
  );
}
